services:
  chrome:
    image: seleniarm/standalone-chromium:124.0-20240427
    restart: always
    expose:
      - 4444
    shm_size: 2gb
  job:
    image: ghcr.io/scjtqs2/hg8145c-reboot:edge
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=zh_CN.UTF-8
      - SELENIUM_ADDR="http://chrome:4444"
      - LOGIN_URL="http://192.168.1.1"
      - LOGIN_USERNAME=useradmin
      - LOGIN_PASSWORD=password
      - CRONTAB="0 0 * * *"
